# Generated by Django 4.2.18 on 2025-02-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieLibrary', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
